# Generated by Django 5.2 on 2025-12-02 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationAccessPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_access",
                    models.BooleanField(default=False, verbose_name="Доступ"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_user",
                        to="applications.application",
                        verbose_name="Приложение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступ к приложению",
                "verbose_name_plural": "Доступы к приложениям",
            },
        ),
    ]
