# Generated by Django 5.2 on 2025-12-02 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("url", models.URLField()),
            ],
            options={
                "verbose_name": "Приложение",
                "verbose_name_plural": "Приложения",
            },
        ),
        migrations.CreateModel(
            name="OfficeSudTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название проекта"
                    ),
                ),
                (
                    "excel_file",
                    models.CharField(max_length=500, verbose_name="Имя файла Excel"),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Batch ID в БД"
                    ),
                ),
                (
                    "container_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="ID контейнера Docker"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает запуска"),
                            ("running", "В процессе"),
                            ("success", "Завершено"),
                            ("error", "Ошибка"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, null=True, verbose_name="Последняя ошибка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Office.sud задача",
                "verbose_name_plural": "Office.sud задачи",
                "ordering": ["-created_at"],
            },
        ),
    ]
